class Comment:
    def __init__(
        self,
        comment_id,
        text,
        author,
        likes,
        reply_count,
        published_at,

    ):
        # Data from YouTube
        self.comment_id = comment_id
        self.text = text
        self.author = author
        self.likes = likes
        self.reply_count = reply_count
        self.published_at = published_at
        self.category = None

        # Data generated by our system
        self.clean_text = ""
        self.is_question = False
        self.cluster_id = None
        self.score = 0
        self.suggested_reply = ""

    def to_dict(self):
        return {
            "comment_id": self.comment_id,
            "text": self.text,
            "author": self.author,
            "likes": self.likes,
            "reply_count": self.reply_count,
            "published_at": self.published_at,
            "clean_text": self.clean_text,
            "is_question": self.is_question,
            "cluster_id": self.cluster_id,
            "score": self.score,
            "suggested_reply": self.suggested_reply,
            "category": self.category,
        }